### nixdev ###
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
monitor = eDP-1, 1920x1080@144, 0x0, 1
monitor = desc:BNQ BenQ EX2780Q 32M01997019, 2560x1440@144, 1920x70, 1
monitor = desc:Samsung Electric Company LS27C33xG H9TWB00353, 1920x1080@100, -1920x70, 1
monitor = desc:ASUSTek COMPUTER INC PA248QV N1LMQS146369, 1920x1200@75, 3840x250, 1
monitor = HEADLESS-1,1920x1080@60,0x1080,1
monitor = desc:Samsung Electric Company S27C31x H4CW500408H, 1920x1080@75, -1920x-300, 1
monitor = desc:Samsung Electric Company S22F350 HCNRB00826, 1920x1080@60, -3000x-900, 1, transform, 3

monitor = desc:ASUSTek COMPUTER INC PA248QV N1LMQS146369, 1920x1200@75, 1920x-300, 1 

monitor = desc:Samsung Electric Company S24R35A H4TT303101, 1920x1080@75, 1920x0, 1
monitor = desc:Samsung Electric Company S22F350 HCNT201138, 1920x1080@60, 3840x0, 1
monitor = desc:Hewlett Packard HP E202 6CM9471555, 1600x900@60, 3840x0, 1, transform, 1



# Monitor 1 
exec-once = sh -c 'VIDEO=$(find "/home/aaron/Videos/wallpapers" -type f \( -iname "*.mp4" -o -iname "*.webm" -o -iname "*.mkv" -o -iname "*.gif" \) | shuf -n 1); [ -n "$VIDEO" ] && mpvpaper -o "--loop --no-audio --hwdec=auto --input-ipc-server=/tmp/mpvsocket-screen1 --panscan=1.0" "desc:AU Optronics 0x7EAD 0x00007EAD" "$VIDEO"'

# Monitor 2 
exec-once = sh -c 'VIDEO=$(find "/home/aaron/Videos/wallpapers" -type f \( -iname "*.mp4" -o -iname "*.webm" -o -iname "*.mkv" -o -iname "*.gif" \) | shuf -n 1); [ -n "$VIDEO" ] && mpvpaper -o "--loop --no-audio --hwdec=auto --input-ipc-server=/tmp/mpvsocket-screen2 --panscan=1.0" "desc:Samsung Electric Company S22F350 HCNT201138" "$VIDEO"'

# Monitor 3 
exec-once = sh -c 'VIDEO=$(find "/home/aaron/Videos/wallpapers" -type f \( -iname "*.mp4" -o -iname "*.webm" -o -iname "*.mkv" -o -iname "*.gif" \) | shuf -n 1); [ -n "$VIDEO" ] && mpvpaper -o "--loop --no-audio --hwdec=auto --input-ipc-server=/tmp/mpvsocket-screen3 --panscan=1.0" "desc:Hewlett Packard HP E202 6CM9471555" "$VIDEO"'

# Auto-pause (with delay so mpvpaper starts first)
exec-once = sleep 5 && ~/gits/mpvpaper-stop/build/mpvpaper-stop -p /tmp/mpvsocket-screen1 --fork
exec-once = sleep 5 && ~/gits/mpvpaper-stop/build/mpvpaper-stop -p /tmp/mpvsocket-screen2 --fork
exec-once = sleep 5 && ~/gits/mpvpaper-stop/build/mpvpaper-stop -p /tmp/mpvsocket-screen3 --fork

exec-once = waybar


# mpvpaper-stop compilation
# mkdir -p ~/gits
# cd ~/gits
# git clone https://github.com/pvtoari/mpvpaper-stop.git
# cd mpvpaper-stop

# meson setup build
# meson compile -C build

# # nix-shell -p meson ninja pkg-config cjson --run '
# #   meson setup build
# #   meson compile -C build
# # '
# cd ~/gits/mpvpaper-stop && rm -rf build && nix-shell -p meson ninja pkg-config gcc cjson --run '
#   meson setup build &&
#   meson compile -C build
# '