.\" Man page for crt_resolution
.\" Generated for RetroPie CRT setup
.TH CRT_RESOLUTION 1 "2025-04-24" "1.0" "User Commands"
.SH NAME
crt_resolution \- Configure CRT display resolutions for RetroPie
.SH SYNOPSIS
.B crt_resolution
[\fB\-h\fR|\fB\-\-help\fR]
[\fB\-v\fR|\fB\-\-verbose\fR]
[\fB\-s\fR|\fB\-\-screen\fR \fIname\fR]
[\fB\-x\fR|\fB\-\-horizontal\fR \fIpixels\fR]
[\fB\-y\fR|\fB\-\-vertical\fR \fIlines\fR]
[\fB\-i\fR|\fB\-\-interlaced\fR [\fIy|n\fR]]
[\fB\-L\fR|\fB\-\-left-margin\fR \fIpixels\fR]
[\fB\-R\fR|\fB\-\-right-margin\fR \fIpixels\fR]
[\fB\-T\fR|\fB\-\-top-margin\fR \fIlines\fR]
[\fB\-B\fR|\fB\-\-bottom-margin\fR \fIlines\fR]
[\fB\-X\fR|\fB\-\-scale-horizontal\fR \fIfactor\fR]
[\fB\-Y\fR|\fB\-\-scale-vertical\fR \fIfactor\fR]
[\fB\-r\fR|\fB\-\-refresh\fR \fIhz\fR]
[\fB\-n\fR|\fB\-\-custom-mode-name\fR \fIname\fR]
[\fB\-m\fR|\fB\-\-run-mode\fR [\fIy|n\fR]]
[\fB\-p\fR|\fB\-\-print-modeline-only\fR [\fIy|n\fR]]
.SH DESCRIPTION
.B crt_resolution
is a Bash script that configures custom CRT display resolutions for RetroPie, using
.B xrandr
to set modelines generated by
.B cvt
. It supports progressive (e.g., 640x240@60Hz) and interlaced (e.g., 640x480@30Hz) modes, with adjustable margins and scaling for overscan correction on CRT TVs (horizontal sync 15\(en35 kHz). Designed for VGA-1 output on Debian-based systems with Intel GPUs, it ensures compatibility with EmulationStation and retro gaming. The default horizontal resolution is 640 pixels, so
.B \-x 640
is optional.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message and exit.
.TP
.BR \-v ", " \-\-verbose
Enable verbose output for debugging (e.g., modeline parameters, timings).
.TP
.BR \-s ", " \-\-screen " <name>"
Set output screen (default: VGA-1).
.TP
.BR \-x ", " \-\-horizontal " <pixels>"
Set horizontal resolution (default: 640).
.TP
.BR \-y ", " \-\-vertical " <lines>"
Set vertical resolution (default: 240 for progressive, 480 for interlaced).
.TP
.BR \-i ", " \-\-interlaced " [y|n]"
Enable interlaced mode (default: y if no argument, n if not specified).
.TP
.BR \-L ", " \-\-left-margin " <pixels>"
Set left margin for overscan (default: 0).
.TP
.BR \-R ", " \-\-right-margin " <pixels>"
Set right margin for overscan (default: 0).
.TP
.BR \-T ", " \-\-top-margin " <lines>"
Set top margin for overscan (default: 0).
.TP
.BR \-B ", " \-\-bottom-margin " <lines>"
Set bottom margin for overscan (default: 0).
.TP
.BR \-X ", " \-\-scale-horizontal " <factor>"
Set horizontal scale factor (default: 1).
.TP
.BR \-Y ", " \-\-scale-vertical " <factor>"
Set vertical scale factor (default: 1).
.TP
.BR \-r ", " \-\-refresh " <hz>"
Set refresh rate (default: 60 for progressive, 30 for interlaced).
.TP
.BR \-n ", " \-\-custom-mode-name " <name>"
Set custom mode name (default: auto-generated, e.g., 640x480_30.00_ON_640x480_30.00_INTERLACED).
.TP
.BR \-m ", " \-\-run-mode " [y|n]"
Apply mode with
.B xrandr
(default: y).
.TP
.BR \-p ", " \-\-print-modeline-only " [y|n]"
Print the final modeline without applying it (default: n). Cannot be used with
.B \-\-run-mode y
.
.SH EXAMPLES
.TP
Add 640x240@60Hz (progressive) to CRT without margins:
.RS
.B crt_resolution
.RE
.TP
Add 640x480@30Hz (interlaced) to CRT without margins:
.RS
.B crt_resolution -i
.RE
.TP
Add 640x240@60Hz (progressive) with margins, without applying, using a custom mode name:
.RS
.B crt_resolution --interlaced n --left-margin 12 --right-margin 30 --top-margin 12 --bottom-margin 0 --run-mode n --custom-mode-name 240p
.IP
Later, apply the mode:
.RS 4
.B xrandr --output VGA-1 --mode 240p --scale 1x2
.RE
.RE
.TP
Add 640x240@60Hz (progressive) with margins and proper 4:3 aspect ratio:
.RS
.B crt_resolution --interlaced n --left-margin 12 --right-margin 30 --top-margin 12 --bottom-margin 0 --scale-horizontal 1 --scale-vertical 2
.RE
.TP
Add 640x480@30Hz (interlaced) with margins:
.RS
.B crt_resolution --interlaced y --left-margin 12 --right-margin 30 --top-margin 20 --bottom-margin 0 --scale-horizontal 1 --scale-vertical 1
.RE
.TP
Print modeline for 640x240@60Hz (progressive) without applying:
.RS
.B crt_resolution -p
.RE
.SH AUTHOR
Written for RetroPie CRT configuration, April 2025.
.SH BUGS
Report bugs to the project repository or relevant RetroPie forums.
.SH SEE ALSO
.BR xrandr (1),
.BR cvt (1),
.BR retroarch (1)