### whitetower ###

# Monitor 1 - Lenovo
monitor = desc:Lenovo Group Limited L1951p Wide   6V6A4410, 1440x900@60.00Hz,   -1440x350,  1
workspace = 1, monitor:desc:Lenovo Group Limited L1951p Wide   6V6A4410, default:true
workspace = 6, monitor:desc:Lenovo Group Limited L1951p Wide   6V6A4410
exec-once = sh -c 'VIDEO=$(find "/home/aaron/Videos/wallpapers" -type f \( -iname "*.mp4" -o -iname "*.webm" -o -iname "*.mkv" -o -iname "*.gif" \) | shuf -n 1); [ -n "$VIDEO" ] && mpvpaper -o "--loop --no-audio --hwdec=auto --input-ipc-server=/tmp/mpvsocket-lenovo --panscan=1.0" "desc:Lenovo Group Limited L1951p Wide   6V6A4410" "$VIDEO"'
exec-once = sleep 5 && ~/gits/mpvpaper-stop/build/mpvpaper-stop -p /tmp/mpvsocket-lenovo --fork
# Monitor 2 - BenQ
monitor = desc:BNQ BenQ EX2780Q 32M01997019,2560x1440@144, 0x0,1
workspace = 2, monitor:desc:BNQ BenQ EX2780Q 32M01997019, default:true
workspace = 7, monitor:desc:BNQ BenQ EX2780Q 32M01997019
exec-once = sh -c 'VIDEO=$(find "/home/aaron/Videos/wallpapers" -type f \( -iname "*.mp4" -o -iname "*.webm" -o -iname "*.mkv" -o -iname "*.gif" \) | shuf -n 1); [ -n "$VIDEO" ] && mpvpaper -o "--loop --no-audio --hwdec=auto --input-ipc-server=/tmp/mpvsocket-benq --panscan=1.0" "desc:BNQ BenQ EX2780Q 32M01997019" "$VIDEO"'
exec-once = sleep 5 && ~/gits/mpvpaper-stop/build/mpvpaper-stop -p /tmp/mpvsocket-benq --fork
# Monitor 2 - HP
monitor = desc:Hewlett Packard HP L1950 CNK8260PLG, 1280x1024@75.00Hz, 2560x150, 1
workspace = 3, monitor:desc:Hewlett Packard HP L1950 CNK8260PLG, default:true
workspace = 8, monitor:desc:Hewlett Packard HP L1950 CNK8260PLG
exec-once = sh -c 'VIDEO=$(find "/home/aaron/Videos/wallpapers" -type f \( -iname "*.mp4" -o -iname "*.webm" -o -iname "*.mkv" -o -iname "*.gif" \) | shuf -n 1); [ -n "$VIDEO" ] && mpvpaper -o "--loop --no-audio --hwdec=auto --input-ipc-server=/tmp/mpvsocket-hp --panscan=1.0" "desc:Hewlett Packard HP L1950 CNK8260PLG" "$VIDEO"'
exec-once = sleep 5 && ~/gits/mpvpaper-stop/build/mpvpaper-stop -p /tmp/mpvsocket-hp --fork


# monitor = desc:BNQ BenQ EX2780Q 32M01997019,1920x1080@60,0x0,1
# monitor = desc:Lenovo Group Limited L1951p Wide   6V6A4410, disable
# monitor = desc:Hewlett Packard HP L1950 CNK8260PLG, disable


