-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"

-- Set programs that you use
local terminal = "kitty"
local fileManager = "pcmanfm"
local menu = "wofi --show drun"
local browser = "firefox"
local secondbrowser = "firefox"
local ide = "code"

hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + ESCAPE", hl.dsp.exit())
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + SPACE", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(secondbrowser))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(ide))
