-- Program launchers and session-level action keybindings.
--
-- Generated by hyprlang2lua from the old .conf files, then documented in Lua.
-- Keep command strings as plain variables when they are reused or likely to be
-- swapped per machine.

-- Main modifier shared with keybindings.lua.
local mainMod = "SUPER"

-- Default programs launched by the bindings below.
local terminal = "kitty"
local fileManager = "pcmanfm"
local menu = "wofi --show drun"
local browser = "firefox"
local secondbrowser = "firefox"
local ide = "code"

-- Core application and compositor controls.
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + ESCAPE", hl.dsp.exit())
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + SPACE", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(secondbrowser))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(ide))

-- Screenshot selection: grim captures the selected slurp region to a timestamped
-- file in ~/Pictures.
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" \"$HOME/Pictures/screenshot-$(date +'%Y-%m-%d_%H-%M-%S').png\""))

-- Convenience launchers for common desktop apps.
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("steam"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("remmina"))
